language: ruby
cache: bundler
rvm:
- 2.4.1
branches:
  only:
  - master
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: sf+MezC4zWtHSbdiEg4yWGpfzZ4kYceHvFdv1bsR22nmjvUm5ti3TQdiMiCAWWTUb20am9ktWTydHmRA3KxmTW3H/ucDwOaPfkCHlwdAOBdxsnTyBx/iQg8UDUZtMsodbMO76vuZxPRWhi0nQ6jeJeZv1C+vQQylaF4UCJvUsUfPO9Px8oBa76F0zFE2cnT4GecuEP3Aa+BRT0WdlCozGCDCSep2I/j/iSdXhrrqjh0rMxNN7AgRtbDjizClrM1NTHSfbsrmEgK8Wp328GDvzyTkf+MXh/7V2Vk3EYktq78PZH1Xp5/7hfyWh9nRb4shWRRvW3agnQbnvJnIk/VrPLvbG/UJiVnn30lBWLzgt3EzdTE3Fvuy24C2cBZlDta/SoDjlRQRqh7ilUclt/lICrJrz6XxjuS/J7gsZRJK36HODvT5XZmqXvnR6Ozar42xg3b8rAMU66fj4OPoUqlX+kK3YFMOlkLwEf9KxPiNPoEfS3oTr4kc7L/dhu5OvodXrab4y/Tao33Swt9aNqtGGfYFOCCuUhOW3+clce5Xd6SQYYLR9dtuWzUTYxISNFxYcCuYjVJngMpfzGMz8KR7ym9vqr2k20sFFCxftlhOmL1TpOQG/JC8pQdq0eZnr57TIfnaA3pA1ShUIkJpkihBqH9CnST0yslWu9EWRda3uao=
  - secure: wo5tb3ZzUqCuYc2x7hlGlq6126ZbZqW+NPOUl9IXmcK5h/kM1hJNQkYa8A4f/Y29zcnFOd6PWP8F/1VpI0HFkny71GtZ8RPKFrxJnms5bTuXAta2a52XyOb+oqwj/Y/GmPgfKxtBFFlHi7gHtcV+hxbiMzfWOM9z4EQROAYKw0FcwvF7526AAxXBM3nMZM3fBcugsoAeeEzjM1rvdKwuTdyAk+7Oz3BF/wAeH5565CgiqBmmhYzL/+U2OssXCW6oIywVVoLonKBsYwAjnz9FlVXjewrzktX3T/xScTzAxhjBZMsJnlSjCFsilK4cImBi36hjd9Kivp8G+bB3p6RsnakEYPkayFoZ0/KTxvdDq4gQPQMJUu92t8exOtV9up3swdoKGpqQ3kylag7arBk/l+xFcUX/vkNvXQTQmXzxa+vbdWdTYGZJGAfDLLmBndlxShPm10LPQOcO8W4KF+jkFpo7MJO5Ff0MArgZJGgeBjw/3QYn4DQbCYmUq/5wOCJOJP+RrNRLDKW7a1iIuhJp3JUvt2XjS51cP5CQg+UZ0rROGbWQ/TsyDjJDM8xl/aCxB2FLMxJph7chgl7joinjBqX9tPSr0idPswTMyMPKL2Tui+0E3OLpaLWTei4pEw3kFgF7yaMdxwLq3OIRXglVVHLdMpUrxkCiBNCFq2lhfMQ=
  - secure: Wjfo2ZOLZgCpgqQSszR9ZGS4xrHmtS01TOS9Mj91fU1F1H3hlMlv+9BIbCkXn6XCg5WCRcTOYBYZItMaPwtvAIFeYx5uAXnHElsr2gcJarxofY7+zF31QX61VviXCvrmffrVLdcl7hNwTDbwyVcg4zyTmAaA7Wf014YKRFka6D5v/fIpdDKwBtiMG11GWFMev1Q3NwTrVzFTuyC+Blw1FM9e1sh/l5CSY4zra8gdrM433vn2wdWHCtFX2d9RZxV68wc23RyBFiws6pT9BynJrdfNrOr2RAY5aeqk2r0GMU9ov99J7f3KG4hTjlRJPlhuJjdPWSc3WfcUrlz6JG5wYt+9rWF7Uw/Fqdi8N0tnH9cdj7NU0mH0lGQprfs70SgN7bBUXJLjx2ZEcl1a/kQZj6LKkWdfvzWrTtJk0PhRWWBWNKRziNFbul10gACzs/X4cmFMTa8IuWpYVxvZqN0fnkD/TCL1tMljzta3htOO6+Ooz3hJZ+p2B0PlSV9+bnMTxBl2j6+BOBRl/eePKHK7OunFjF8hWGCyQU8BWNvNZLAvLr75Tr2dU5fdpPcIlIC1AorYyQfZfIggceystCXtH9AhCLvXd+6NDdXyRqlLyLJkWINj3AyfImGRgQJ74ntZOykWcjgVkDTFcJ0Ihxx8WD47/s1pD0PhlEWXNpf81Uk=
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
sudo: false
notifications:
  email: false
script:
- bundle exec jekyll build
- bundle exec rake test
before_install:
- gem install bundler
before_deploy:
- openssl aes-256-cbc -K $encrypted_4208158246d9_key -iv $encrypted_4208158246d9_iv
  -in ./deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- echo -e "Host $DEPLOY_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --quiet --delete-after _site/* $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIRECTORY
  on:
    branch: master
