name: Build and deploy Jekyll site

on:
  push:
    branches:
      - master

jobs:
  build-jekyll-deploy-remote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Build
        uses: jerryjvl/jekyll-build-action@v1
      - name: rsync to remote server
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -vazh
          path: _site/*
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_SSH_KEY }}
